FROM registry.access.redhat.com/ubi8/ubi-minimal:8.1
WORKDIR /work/

COPY url-shorter/target/*-runner /work/application

RUN chmod 775 /work /work/application \
  && chown -R 1001 /work \
  && chmod -R "g+rwX" /work \
  && chown -R 1001:root /work

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]

RUN chmod 775 /work /work/application && chown -R 1001 /work && chmod -R "g+rwX" /work && chown -R 1001:root /work